apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coolstore-user-monitoring
  namespace: coolstore-catalog-dev
rules:
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - '*'
    verbs:
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-monitoring-coolstore-catalog-dev
  namespace: coolstore-catalog-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: coolstore-user-monitoring
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops