{
 "title": "Coolstore User Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "dev,stage" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(inventory_performedChecksAll_counter_total{namespace=\"coolstore-inventory-$environment\"}, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(inventory_performedChecksAll_counter_total{namespace=\"$namespace\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "A counter of how many times getAll() has been performed.",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "inventory_performedChecksAll_counter_total{namespace=\"$namespace\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(inventory_performedChecksAll_timer_seconds_sum{namespace=\"$namespace\", instance=\"$instance\"})/\n(inventory_performedChecksAll_timer_seconds_count{namespace=\"$namespace\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "A counter of how many times getAvailability() is called",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "inventory_checksTimerAvail_timer_seconds_count{namespace=\"$namespace\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(inventory_checksTimerAvail_timer_seconds_sum{namespace=\"$namespace\", instance=\"$instance\"})/\n(inventory_checksTimerAvail_timer_seconds_count{namespace=\"$namespace\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total number of requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{namespace=\"$namespace\",instance=\"$instance\",uri=\"/services/inventory\"}[1h])",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  }
 ]
}