apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: inventory-monitor
  name: inventory-monitor-dev
  namespace: coolstore-inventory-dev
spec:
  endpoints:
    - interval: 30s
      port: metrics
      scheme: http
      path: /q/metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: coolstore-inventory-dev-app
      app.kubernetes.io/name: inventory
      app.kubernetes.io/part-of: coolstore-inventory