{
 "title": "Quarkus Metrics",
 "description": "Generic dashboard for Quarkus apps",
 "tags": [
  "quarkus",
  "microprofile",
  "jvm",
  "java"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(inventory_performedChecksAll_counter_total, namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(process_uptime_seconds{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(process_uptime_seconds{namespace=\"$namespace\", service=\"$service\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_uptime_seconds{pod=\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "Usage for the JVM process. 100% means that all CPUs were actively running threads from the JVM",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_cpu_usage{pod=\"$instance\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Mem",
   "type": "gauge",
   "description": "Used / max heap memory",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{pod=\"$instance\"}*100/jvm_memory_max_bytes{pod=\"$instance\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "HTTP (cluster)",
   "type": "stat",
   "description": "HTTP stats in selected time range for all instances in a cluster.\n\nPlease mind that response time displayed here is measured inside JVM, it is not full end to end latency your users see, which can be few times bigger.\n\nAdd this to your application.properties first:\nquarkus.resteasy.metrics.enabled=true",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(base_REST_request_total{namespace=\"$namespace\", service=\"$service\"}[$__range])))",
     "legendFormat": "Total requests"
    },
    {
     "expr": "round(sum(increase(application_http_request_total{namespace=\"$namespace\", service=\"$service\"}[$__range])))",
     "legendFormat": "Total requests"
    },
    {
     "expr": "sum(increase(base_REST_request_elapsedTime_seconds{namespace=\"$namespace\", service=\"$service\"}[$__range])) / sum(increase(base_REST_request_total{namespace=\"$namespace\", service=\"$service\"}[$__range]))",
     "legendFormat": "Avg response time"
    },
    {
     "expr": "sum(increase(application_http_request_elapsedTime_seconds{namespace=\"$namespace\", service=\"$service\"}[$__range])) / sum(increase(application_http_request_total{namespace=\"$namespace\", service=\"$service\"}[$__range]))",
     "legendFormat": "Avg response time"
    }
   ]
  },
  {
   "title": "Database",
   "type": "bargauge",
   "description": "Add this to your application.properties first:\nquarkus.datasource.metrics.enabled=true",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vendor_agroal_active_count{pod=\"$instance\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(vendor_agroal_available_count{pod=\"$instance\"})",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum(vendor_agroal_max_used_count{pod=\"$instance\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(vendor_agroal_leak_detection_count_total{pod=\"$instance\"})",
     "legendFormat": "Leaks"
    },
    {
     "expr": "sum(round(increase(vendor_agroal_acquire_count_total{pod=\"$instance\"}[$__range])))",
     "legendFormat": "Acquire count"
    }
   ]
  },
  { "title": "HTTP (cluster)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Requests per minute",
   "type": "graph",
   "description": "HTTP avg requests/minute for all instances in a cluster.\n\nAdd this to your application.properties first:\nquarkus.resteasy.metrics.enabled=true",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(base_REST_request_total{namespace=\"$namespace\", service=\"$service\"}[1m])) by (class, method))",
     "legendFormat": "{{class}} {{method}}"
    },
    {
     "expr": "round(sum(increase(application_http_request_total{namespace=\"$namespace\", service=\"$service\"}[1m])) by (method, endpoint))",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Avg server response times",
   "type": "graph",
   "description": "HTTP average response times over last [1m] for all instances in a cluster.\n\nPlease mind that response time displayed here is measured inside JVM, it is not full end to end latency your users see, which can be few times bigger.\n\nAdd this to your application.properties first:\nquarkus.resteasy.metrics.enabled=true",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(increase(base_REST_request_elapsedTime_seconds{namespace=\"$namespace\", service=\"$service\"}[1m]) / increase(base_REST_request_total{namespace=\"$namespace\", service=\"$service\"}[1m]) > 0) by (method, endpoint) ",
     "legendFormat": "Average {{class}} {{method}}"
    },
    {
     "expr": "avg(increase(application_http_request_elapsedTime_seconds{namespace=\"$namespace\", service=\"$service\"}[1m]) / increase(application_http_request_total{namespace=\"$namespace\", service=\"$service\"}[1m]) > 0) by (method, endpoint) ",
     "legendFormat": "Average {{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Http errors (400s & 500s)",
   "type": "graph",
   "description": "You need quarkus-rfc7807-problem-extension dependency + quarkus.rfc7807-problem.metrics.enabled=true setting in application.properties",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (round(increase(application_http_error_total{namespace=\"$namespace\", service=\"$service\", status=~\"5.*\"}[1m])))",
     "legendFormat": "HTTP {{status}}"
    },
    {
     "expr": "sum by (status) (round(increase(application_http_error_total{namespace=\"$namespace\", service=\"$service\", status=~\"4.*\"}[1m])))",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  { "title": "Hardware utilisation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Displays  the \"recent cpu usage\" for the Java Virtual Machine process. This value is a double in the [0.0,1.0] interval. A value of 0.0 means that none of the CPUs were running threads from the JVM process during the recent period of time observed, while a value of 1.0 means that all CPUs were actively running threads from the JVM 100% of the time during the recent period being observed. Threads from the JVM include the application threads as well as the JVM internal threads. All values betweens 0.0 and 1.0 are possible depending of the activities going on in the JVM process and the whole system. If the Java Virtual Machine recent CPU usage is not available, the method returns a negative value.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(base_cpu_processCpuLoad_percent{pod=\"$instance\"})",
     "legendFormat": "Usage for the JVM process. 100% means that all CPUs were actively running threads from the JVM"
    },
    {
     "expr": "sum(avg_over_time(base_cpu_processCpuLoad_percent{pod=\"$instance\"}[1h]))",
     "legendFormat": "Usage for the JVM process - last hour average"
    },
    {
     "expr": "sum(vendor_cpu_systemCpuLoad_percent{pod=\"$instance\"})",
     "legendFormat": "Usage for the whole system. 100% means that all CPUs were actively running 100% of the time"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "description": "The system load average is the sum of the number of runnable entities queued to the available processors and the number of runnable entities running on the available processors averaged over a period of time. The way in which the load average is calculated is operating system specific but is typically a damped time-dependent average. If the load average is not available, a negative value is displayed. This attribute is designed to provide a hint about the system load and may be queried frequently. The load average may be unavailable on some platforms where it is expensive to implement this method.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(base_cpu_systemLoadAverage{pod=\"$instance\"})",
     "legendFormat": "System load average for the last minute"
    },
    {
     "expr": "sum(base_cpu_availableProcessors{pod=\"$instance\"})",
     "legendFormat": "Number of processors available to the JVM"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(base_thread_count{pod=\"$instance\"}-base_thread_daemon_count{pod=\"$instance\"})",
     "legendFormat": "Live threads"
    },
    {
     "expr": "sum(base_thread_daemon_count{pod=\"$instance\"})",
     "legendFormat": "Live daemon threads"
    },
    {
     "expr": "sum(base_thread_count{pod=\"$instance\"})",
     "legendFormat": "Live threads total"
    },
    {
     "expr": "sum(base_thread_max_count{pod=\"$instance\"})",
     "legendFormat": "Peak live threads total"
    }
   ]
  },
  {
   "title": "Container Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(base_memory_maxHeap_bytes{pod=\"$instance\"})",
     "legendFormat": "Max heap"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=\"$instance\"})",
     "legendFormat": "Container working set"
    },
    {
     "expr": "sum(vendor_memory_freeSwapSize_bytes{pod=\"$instance\"})",
     "legendFormat": "Free swap space"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{pod=\"$instance\"})",
     "legendFormat": "Container limit"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Heap",
   "type": "graph",
   "description": "Java objects reside in an area called the heap. The heap is created when the JVM starts up and may increase or decrease in size while the application runs. When the heap becomes full, garbage is collected. During the garbage collection objects that are no longer used are cleared, thus making space for new objects.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(base_memory_usedHeap_bytes{pod=\"$instance\"})",
     "legendFormat": "Used heap memory"
    },
    {
     "expr": "sum(base_memory_committedHeap_bytes{pod=\"$instance\"})",
     "legendFormat": "Memory committed (guaranteed) for the JVM to use"
    },
    {
     "expr": "sum(base_memory_maxHeap_bytes{pod=\"$instance\"})",
     "legendFormat": "Maximum amount (not guaranteed) of heap memory that can be used for memory management"
    }
   ]
  },
  {
   "title": "Heap Memory Pools",
   "type": "graph",
   "description": "Memory Pools are created by JVM memory managers to create a pool of immutable objects. Memory Pool can belong to Heap or Perm Gen, depending on JVM memory manager implementation.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "repeat": "jvm_memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (vendor_memoryPool_usage_bytes{pod=\"$instance\"})",
     "legendFormat": "Usage {{name}}"
    },
    {
     "expr": "sum by (name) (vendor_memoryPool_usage_max_bytes{pod=\"$instance\"})",
     "legendFormat": "Max {{name}}"
    }
   ]
  },
  {
   "title": "Non-Heap",
   "type": "graph",
   "description": "The JVM has memory other than the heap, referred to as Non-Heap Memory. It is created at the JVM startup and stores per-class structures such as runtime constant pool, field and method data, and the code for methods and constructors, as well as interned Strings. The default maximum size of non-heap memory is 64 MB.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_memory_usedNonHeap_bytes{pod=\"$instance\"})",
     "legendFormat": "Used non-heap memory"
    },
    {
     "expr": "sum(vendor_memory_committedNonHeap_bytes{pod=\"$instance\"})",
     "legendFormat": "Non heap memory committed (guaranteed) for the JVM to use"
    },
    {
     "expr": "sum(vendor_memory_maxNonHeap_bytes{pod=\"$instance\"})",
     "legendFormat": "Maximum amount of used non-heap memory"
    }
   ]
  },
  {
   "title": "Class Loader",
   "type": "graph",
   "description": "Class loaders are responsible for loading Java classes during runtime dynamically to the JVM (Java Virtual Machine). Also, they are part of the JRE (Java Runtime Environment). Hence, the JVM doesn't need to know about the underlying files or file systems in order to run Java programs thanks to class loaders.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(base_classloader_loadedClasses_count{pod=\"$instance\"})",
     "legendFormat": "Classes currently loaded in the JVM"
    },
    {
     "expr": "sum(delta(base_classloader_loadedClasses_count{pod=\"$instance\"}[1m]))",
     "legendFormat": "Classes currently loaded in the JVM - delta 1m"
    }
   ]
  },
  { "title": "Datasource (Agroal)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Connection pool over last [1m]",
   "type": "graph",
   "description": "Add this to your application.properties first:\nquarkus.datasource.metrics.enabled=true",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_agroal_active_count{pod=\"$instance\"})",
     "legendFormat": "Active connections"
    },
    {
     "expr": "sum(vendor_agroal_available_count{pod=\"$instance\"})",
     "legendFormat": "Idle connections, available to be acquired"
    },
    {
     "expr": "sum(increase(vendor_agroal_creation_count_total{pod=\"$instance\"}[1m]))",
     "legendFormat": "Created connections in the last minute"
    },
    {
     "expr": "sum(increase(vendor_agroal_destroy_count_total{pod=\"$instance\"}[1m]))",
     "legendFormat": "Destroyed connections last minute"
    },
    {
     "expr": "sum(vendor_agroal_max_used_count{pod=\"$instance\"})",
     "legendFormat": "Maximum number of connections active simultaneously"
    },
    {
     "expr": "sum(increase(vendor_agroal_leak_detection_count_total{pod=\"$instance\"}[1m]))",
     "legendFormat": "Leak detections"
    }
   ]
  },
  {
   "title": "Timing over last [1m]",
   "type": "graph",
   "description": "Add this to your application.properties first:\nquarkus.datasource.metrics.enabled=true",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vendor_agroal_blocking_time_total_seconds{pod=\"$instance\"}[1m]))",
     "legendFormat": "Time to acquire a connection"
    },
    {
     "expr": "sum(rate(vendor_agroal_creation_time_total_seconds{pod=\"$instance\"}[1m]))",
     "legendFormat": "Time to create a connection"
    },
    {
     "expr": "avg(increase(application_db_query_elapsedTime_seconds{pod=\"$instance\"}[1m]) / increase(application_db_query_total{pod=\"$instance\"}[1m])) by (group, operation)",
     "legendFormat": "Sql: {{group}} {{operation}}"
    }
   ]
  },
  { "title": "Garbage Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Collections over last [1m]",
   "type": "graph",
   "description": "JVM garbage collectors summary:\nhttps://www.baeldung.com/jvm-garbage-collectors",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (increase(base_gc_total{pod=\"$instance\"}[1m]))",
     "legendFormat": "Number of collections that have occurred last minute ({{name}})"
    }
   ]
  },
  {
   "title": "Durations over last [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (increase(base_gc_time_total_seconds{pod=\"$instance\"}[1m]))",
     "legendFormat": "Approximate accumulated collection elapsed time ({{name}})"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "{pod=\"$instance\"}"
    }
   ]
  }
 ]
}