kind: Grafana
apiVersion: integreatly.org/v1alpha1
metadata:
  namespace: coolstore-monitoring
  name: coolstore-grafana
spec:
  config:
    log:
      mode: "console"
      level: "warn"
    auth:
      disable_login_form: False
      disable_signout_menu: True
    auth.basic:
      enabled: True
    auth.anonymous:
      enabled: True
  ingress:
    enabled: True
  client:
    preferService: True