apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coolstore-user-monitoring
  namespace: coolstore-inventory-stage
rules:
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - '*'
    verbs:
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-grafana
  namespace: coolstore-inventory-stage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: coolstore-user-monitoring
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops