apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: inventory-monitor
  name: inventory-monitor-stage
  namespace: coolstore-inventory-stage
spec:
  endpoints:
    - interval: 30s
      path: /q/metrics
      port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/component: quarkus-service
      app.kubernetes.io/instance: coolstore-inventory-stage-app
      app.kubernetes.io/name: inventory
      app.kubernetes.io/part-of: coolstore-inventory