apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - session-secret.yaml
  - grafana-proxy-rbac.yaml
  - grafana.yaml
  - patch-openshift-gitops-application-controller-role.yaml