apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manage-grafana
  namespace: coolstore-monitoring
rules:
  - apiGroups:
      - integreatly.org
    resources:
      - '*'
    verbs:
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-grafana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manage-grafana
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops